language: node_js
node_js:
  - "11"

stages:
  - test
  - name: deploy
    if: branch = master

cache:
  directories:
    - "node_modules"

install:
    - npm install
    - npm install codecov -g

after_success:
  - codecov --token=$CODECOV_TOKEN"

jobs:
  include:
    - stage: test
      script:
          - echo "Running tests against $(node -v) ..."
          - npm run test
          
    - stage: deploy
      script: echo "Deploying to npm ..." && npm run publish-me
      deploy:
        email: ahryman40k.gb@gmail.com
        provider: npm
        api_key: $NPM_API_KEY